### ISSUE TITLE
[Tock Bot Admin] Customisable html base href 

### ISSUE THREAD

**Issue by msansen1** [theopenconversationkit/tock#1047]
Hi,

i'd like to expose bot admin with a specific path uri like example.com/bot/admin/

but in the file tock/bot/admin/web/src/index.html

there is a base href tag : ` <base href="/">`

Is it possible to change it?

Regards

Mat

**Comment by vsct-jburet** [comment]
See #406

**Comment by francoisno** [comment]
Hello @msansen1 thx for the issue. As @vsct-jburet it is probably the same issue as #406 (still to resolve).
We will search for a solution (preferably at runtime) for this "classic" Angular issue (eg. https://angular.io/guide/deployment#the-base-tag)

**Comment by vsct-jburet** [comment]
We will fix it with a rewrite in AdminVerticle of index.html

**Comment by msansen1** [comment]
Hello @vsct-jburet and @francoisno, you're right it's the same issue as #406. thanks for it.

**Comment by vsct-jburet** [comment]
Fixed
