### ISSUE TITLE
Removed-language labels cannot be purged

### ISSUE THREAD

**Issue by francoisno** [theopenconversationkit/tock#1063]
Currently when a language is removed from an application:

- The answers still exist in database
- Requesting the bot through the removed language can result in those "remaining" asnwers (https://github.com/theopenconversationkit/tock/issues/1062)
- Yet the removed language is not visible/testable in Tock Studio
- It is not easy to access those answers from Tock Studio to remove them

Removing the language should rather:
 
- Purge the answers
- Or give means to find them / remove them in Tock Studio

Plus requesting a removed language should not respond with that language : https://github.com/theopenconversationkit/tock/issues/1062

**Comment by vsct-jburet** [comment]
if #1062 is fixed, what is the issue with keeping the labels in db? because if you remove a language, this could lead to a big oops to remove all the translations ;)

**Comment by francoisno** [comment]
@vsct-jburet I agree removing translations at once would be risky. Rather give a mean to remove them later, for instance an application-level button to "prune" all removed translations, or some "see disabled languages" filter in i18n to make them visible?
The fix/feature was asked by Marvin, let's discuss with them again ;)

**Comment by francoisno** [comment]
Marvin OK to let see/filter disabled languages in i18n aka _Answers_ view (making possible to remove labels without automating it).
