### ISSUE TITLE
Issue to change several sentences from un intent to another one

### ISSUE THREAD

**Issue by MorganeAbadie** [theopenconversationkit/tock#1100]
On the table view, when sentences are selected to change them to another intent, it doesn't work anymore.
I think there is a regression on this functionality.

Below you can see the error message appearing once I cliked on "change intent" button.
You can see that the sentences are not selected but they were before I clicker on the button.
![pb_change_intent](https://user-images.githubusercontent.com/54838256/97897671-1a80fd80-1d37-11eb-8a01-03f91e04ffbb.png)

Test done on versions 20.9.0 and 20.9.1 (online demo).

**Comment by vsct-jburet** [comment]
the bug is present only for the unknown intent
