### ISSUE TITLE
Import Application Dump programatically (Integrated mode) 

### ISSUE THREAD

**Issue by psylvestre** [theopenconversationkit/tock#1112]
As importNlpDump, it should be interesting to programmatically export and import the complete data model. So we could start a bot with the complete configuration wihtout using Tock Studio.

**Comment by francoisno** [comment]
As discussed, new feature requests have been created for more export/import possibilites:

- Import of sentences #1021 
- Export/import configurations #1152 
- Export/import rules #1153  
- Export/import full bot incl. everything #1154 or #779
