### ISSUE TITLE
Problème pour faires des actions de "masse" sur des phrases de l'admin

### ISSUE THREAD

**Issue by MorganeAbadie** [theopenconversationkit/tock#1114]
Suite à la montée de version Tock 20.9.1, j'ai remarqué qu'il n'était plus possible de supprimer plusieurs phrases à la fois de l'inbox.
En effet, quand on passe en table view, que l'on sélectionne plusieurs phrases et qu'on clique sur "delete" tout bug, l'interface devient inutilisable et après rechargement de la page, les phrases n'ont pas été supprimées.

Idem pour la bascule de plusieurs phrases en table view, si on sélectionne un intent de la base cela fonctionne mais il est impossible de le faire sur le unknown. Je ne sais pas ici si c'est une régression sur cette version car je n'avais jamais effectuer l'action avant.

**Comment by MorganeAbadie** [comment]
Problème similaire de "freeze" lorsque l'on supprime un story et qu'on était dedans
![bug_delete_story](https://user-images.githubusercontent.com/54838256/99940955-7b678880-2d6d-11eb-8908-cc5d26c6f43b.JPG)

**Comment by francoisno** [comment]
Bonjour @MorganeAbadie,

Merci de nous avoir remonté cette régression.
Le problème est corrigé dans la pull request #1117 (dans la prochaine release 20.9.2 / novembre).
