### ISSUE TITLE
Nombre d'action inexact lors du renvoi au connector

### ISSUE THREAD

**Issue by psylvestre** [theopenconversationkit/tock#1116]
Repository :
https://github.com/psylvestre/tock-edf

Contexte :
- Bot EDF
- Connector A lié au Bot EDF
- Connector B lié au Bot EDF
- Story 01 renvoie un texte
- Story 02 renvoie les actions lié au Connector A
- Les appels se font via des requêtes HTTP

Scénario :
1 - Avec le Connector A, je déclenche la Story 01 -> Génère 2 actions sur le Connector A
2 - Avec le Connector B, je déclenche la Story 02 -> Trouve et renvoie les 2 actions lié au Connector A
3 - Avec le Connector A, je déclenche la Story 01 -> Génère 2 actions supplémentaires sur le Connector A
4 - Avec le Connector B, je déclenche la Story 02 -> Trouve 4 actions lié au Connector A
                                                                               -> **Mais ne renvoie que les 2 premières actions**

Question : 
- **Pourquoi lors du second appel de la story ne me renvoie pas les 4 actions ?**

Ci-dessous quelques lignes de story.
![image](https://user-images.githubusercontent.com/73884191/99789683-423bd800-2b23-11eb-9430-574f91599576.png)

1) A la ligne 39 de la story on log le json à renvoyer, et on constate qu'on a bien les 4 actions.
2) Dans les logs du bot on a la ligne suivante :
![image](https://user-images.githubusercontent.com/73884191/99790322-38ff3b00-2b24-11eb-996a-a3ca84c3daa8.png)
On voit le message envoyé par le TockConnectorController en bleu avec le json renvoyé. Celui-ci correspond au premier déclenchement de la story 02, donc avec seulement 2 actions.

Merci de votre aide.

**Comment by vsct-jburet** [comment]
@psylvestre le module de traduction automatique est activé dans le bot:         

```kotlin
        //enable i18n as two locales are supported
        Translator.enabled = true

```

Sur le premier appel du connector B, Tock va donc chercher une traduction du libellé - il ne le trouve pas et persiste donc la traduction "ISO" en base avec une clé correspondant aux 512 premiers caractères.

Sur le deuxième appel, il recherche si la clé existe - comme le json est gros, les 512 premiers caractères sont les mêmes - le module de traduction retourne donc la valeur du premier appel.

Pour éviter ce problème, 3 solutions

- désactiver le modèle de traduction (c'est le cas par défaut dans Tock)

- utiliser l'extension .raw:

```kotlin
end(mapper.writeValueAsString(conversation).raw)
```

- utiliser endRawText

```kotlin
endRawText(mapper.writeValueAsString(conversation))
```
