### ISSUE TITLE
[Doc] Improve slightly Slack integration guide

### ISSUE THREAD

**Issue by djowalker** [theopenconversationkit/tock#1147]
Hello, Slack integration french guide, seems to lack some simple steps to fastly understand how it works.

The steps missing are : 
- that you shouldn't forget to add the bot user in the channel
- the differents types of bot events you are able to to subscribe : message.channels/groups/im
- Do not forget that when you reinstall the app in workspace, the webhook url has change, especially for the token 2 and 3.

Without these elements, first steps with Tock and Slack can be complicated.

**Comment by francoisno** [comment]
Thx @djowalker for this.
I've just pushed an update (still as a draft PR), it is ok for you?

https://github.com/theopenconversationkit/tock/pull/1149/files#diff-772d357fae31b4766944036d97a89972f85b27da90e0987f5b5c7f5adfa94de6
