### ISSUE TITLE
Build a Carousel Story inside Tock Studio

### ISSUE THREAD

**Issue by msansen-esncf** [theopenconversationkit/tock#1166]
Hi Tock Team,

i have a bot usage that is only made of fullText queries answers.
Some complex queries are answered with full text carrousels.

ask me if you need a sample.

So my question is: Is it possible to build carrousels inside a story.

If we can do this so we will be able to manage all the bot from studio as a NO-CODE-BOT

Thanks for your help

Regards

Mat

**Comment by msansen-esncf** [comment]
It it's too difficult to add it with simple User interface, one possibility can be to enable adding some stories made of code blocks?

**Comment by francoisno** [comment]
Hi Mathieu. Thx for the feature request.
For now it is only possible to create caroussels using code, but it would be nice to create them in Tock Studio (like creating Cards / Media answers).
To be tested: _Script_ Stories might already make it possible to include caroussels answers as code through Tock Studio.

**Comment by msansen-esncf** [comment]
Hi, 

The script story return: 
Compilation error:  Unresolved reference: newCarousel

it seems it's unrecognized by script story.

**Comment by vsct-jburet** [comment]
@msansen-esncf 

This should work for the teams connector in a scripted story:

```kotlin
import ai.tock.bot.connector.teams.messages.teamsCarousel
import ai.tock.bot.connector.teams.messages.teamsMessage
import ai.tock.bot.connector.teams.messages.withTeams
import ai.tock.bot.definition.story

val s = story("test") {
    withTeams {
        teamsCarousel(
            listOf(
                teamsMessage("card 1"),
                teamsMessage(" card 2")
            )
        )
    }

    end()
}
```

you can find the api here: http://doc.tock.ai/tock/dokka/tock/ai.tock.bot.connector.teams.messages/index.html
