### ISSUE TITLE
[Studio] Basic Q&A management proposal

### ISSUE THREAD

**Issue by jygdev** [theopenconversationkit/tock#1168]
Hi,

As Arkea's conversational team we receive many requests for basic Q&A chatbots creation.
It is currently hard for people not familiar with Tock or conversational concepts to create this kind of bot by themselves into the Studio.
We would like to propose a new user experience to be included into the studio to handle such use cases and give our customers more autonomy with their basic Q&A bots creation and content management.

We designed few mockups (see attachment) of how we could add this to the studio based on needs we have collected from our customers.
We would be happy to discuss further this proposal with anyone interested before strating developing this new feature.
Feel free to ask questions if everything isn't clear enough in the mockups.

Regards,

[TOCK FAQ.pdf](https://github.com/theopenconversationkit/tock/files/5874205/TOCK.FAQ.pdf)

**Comment by vsct-jburet** [comment]
merged, thank you !
