### ISSUE TITLE
[Core] Fast action-tree navigation with entities

### ISSUE THREAD

**Issue by francoisno** [theopenconversationkit/tock#1172]
_Feature asked by Amine B. for SNCF DOSN 'ED bot'._

When developing a _Configured Story_ (using _Tock Studio_) with a tree of _Actions_ navigating by _Entities_, it would be nice to allow to skip some question-answer user cycles when multiple entities are given at once.

Example (for now):
- User: I want _information_ about _x_
- (Story: detecting entity _information_ triggers action A)
- Bot: What do you want info about?
- User: About _x_
- (Story: detecting entity _x_ triggers sub-action SA)
- Bot: Here is info about x...

Example (new feature target):
- User: I want _information_ about _x_
- (Story: detecting entity _information_ triggers action A, then detecting entity _x_ triggers sub-action SA)
riggers sub-action SA)
- Bot: Here is info about x...

Please add an optional Tock property to enable/disable this feature, to prevent eventual impact on complex trees.

**Comment by msansen-esncf** [comment]
Thank you Francois for this issue.

what we would like to have is to brows deeper into entity tree to give immdiately the right answer without answering a one entity only answer


suppose a story like tools

1. _gmail_: answer: A powerfull mail client on cloud
(sub entities;)
- link : mail.google.com
- subscribe: mail.google.com/subscribe

2. outlook: answer: A powerfull mail client

- pst : file that store your messages


if it detect entity tool gmail an entity link : directly answer mail.google.com

is it clear?

Regards

Mat

**Comment by vsct-jburet** [comment]
The tree :
![image](https://user-images.githubusercontent.com/12413454/107150786-efbeca80-695f-11eb-88c6-aec0733a190f.png)

gives:

![image](https://user-images.githubusercontent.com/12413454/107150815-02d19a80-6960-11eb-990f-ebe0b10ee1b8.png)

@francoisno I think the tock property is not required, as regression are unlikely to happen

**Comment by francoisno** [comment]
@vsct-jburet I was thinking about Configured Stories implementing step-by-step answer trees. Skipping the intermediate answers might result in strange dialogs ; deep answers should probably be reworked taking fast-navigation possibility into account.

**Comment by vsct-jburet** [comment]
For now the feature works only with two entities in the same action, so this is really a corner case :)

**Comment by msansen-esncf** [comment]
Hi Julien and Francois,

Thank for your work on this feature.

Maybe am wrong but i can't find he button to add an entity on anoher entity:

![image](https://user-images.githubusercontent.com/60747886/107490771-9e465380-6b8a-11eb-822a-f7abce09a30f.png)

same in 20.9.3 and 21.3 snap on demo
Thanks for your help

Regards

Mat
