### ISSUE TITLE
bot_admin: not in debug with - tock_env=dev

### ISSUE THREAD

**Issue by msansen-esncf** [theopenconversationkit/tock#1201]
Hi, 
To have debug logs on bot_admin i moved from - tock_env=prod to - tock_env=dev but it stay in INFO
I added - tock_default_log_level=DEBUG and it was in DEBUG mode

is it as expected?

Regards

Mat

**Comment by francoisno** [comment]
Hi @msansen-esncf could you please give an example of a logline you expect to be `DEBUG` with `tock_env=dev` please, so that I can reproduce and see what happens here?

**Comment by msansen-esncf** [comment]
hello @francoisno it seems that for admin it is different. No need to check it anymore. THanks for your help
