### ISSUE TITLE
Analytics > "Messages by Story" issue - Story rule

### ISSUE THREAD

**Issue by MorganeAbadie** [theopenconversationkit/tock#1203]
I have a chatbot dedicated to 2 targets : clients and advisors. Most of the knowledge are similar but for some of them, different answers have been set up. 
To do so, here we are what we have done : 
1/ Create 2 different connectors
![image](https://user-images.githubusercontent.com/54838256/109510880-cd255a80-7aa2-11eb-99f5-e8a28bd86fb7.png)
2/ Create 2 different intents to get 2 stories. However, all sentence are qualified only on 1 of the 2 intents:
parler_humain : story for clients
parler_humain_cons : story for advisors
![image](https://user-images.githubusercontent.com/54838256/109511579-78ceaa80-7aa3-11eb-85b0-6b65d958ec7e.png)

parler_humain : intent on which all sentences are qualified
![image](https://user-images.githubusercontent.com/54838256/109511464-58065500-7aa3-11eb-876e-ab3875d43a2c.png)
![image](https://user-images.githubusercontent.com/54838256/109511509-66547100-7aa3-11eb-95e3-f3f8edf7fc4d.png)

3/ Story rule has been set up in order to redirect all "parler_humain" intents to the "parler_humain_cons" story for the advisor connector
![image](https://user-images.githubusercontent.com/54838256/109511754-a7e51c00-7aa3-11eb-9b35-12a303a7cf86.png)

Everything is working fine on the front interface : clients get their client answer and advisors get their advisor answer
However, in the statistics, this is not what we have as "parler_humain_cons" stories are found in clients connector which is not possible : 
![image](https://user-images.githubusercontent.com/54838256/109512131-0dd1a380-7aa4-11eb-8589-bc6657487e9f.png)

I don't know where the error can come from.

Could you please help me ?

**Comment by francoisno** [comment]
Hi @MorganeAbadie,

Just to be sure: the statistics you get are for the clients connector only? (not both configurations/connectors ?)

I guess it could be:

- either a configuration/connector filter issue on Analytics,
- or maybe a story gets a hit in stats, even when redirected by rules.

Hopefully I will soon find out :)

**Comment by MorganeAbadie** [comment]
Hi @francoisno ,

Yes, the graph shows only results filtered on client connector.

Hope so to :)
