### ISSUE TITLE
Analytics > Differences between messages by intent and by story

### ISSUE THREAD

**Issue by MorganeAbadie** [theopenconversationkit/tock#1212]
I have a question regarding the count of the statistics : why sometimes, the number of intent sollicitation and story sollicitation are different while I know the intent redirect only to this story ?

You can see an example below with the unknown story:
Messages by story (high number in February the 2nd)
![image](https://user-images.githubusercontent.com/54838256/109773969-1b9c3b80-7c00-11eb-9ae5-aacce3e7c3bf.png)

Messages by intent
![image](https://user-images.githubusercontent.com/54838256/109774019-2d7dde80-7c00-11eb-9082-1a2fa84c3ce3.png)

Thanks

**Comment by francoisno** [comment]
Hi @MorganeAbadie,

As you stated it, a sentence is qualified with an intent, which triggers a story.
Yet, a story can be triggered by other stories or other intents than its "main intent", for instance: redirecting to stories through _Story Rules_ (the original sentence intent may be different than the triggered-story main intent).

In the particular case of _unknown_ intents/stories, there is another mecanism possibly explaining this: a sentence, with a low intent-detection score may be under the _unknow threshold_ (set at application level), triggering the _unknown_ story even if the _unknown_ intent was not detected.
These are possible explanations, does it make sense to you?

**Comment by MorganeAbadie** [comment]
Hi @francoisno,

Yes totally, I didn't think about these possibilities. It makes me better understand how it works.
