### ISSUE TITLE
No picture with base_href settings

### ISSUE THREAD

**Issue by Houpert** [theopenconversationkit/tock#1239]
Hello, 

While using base_href settings with docker it's appear to not have any picture :
![NotFound](https://user-images.githubusercontent.com/6594652/112282040-0195cc00-8c87-11eb-8a4d-ce40fe5178d1.png)

The bug appear on both image **nlp_admin** and **bot_admin**.

Here the env settings for both docker :
```
tock/nlp_admin : adminverticle_base_href=/tock
tock/bot_admin : botadminverticle_base_href=/tock
```

Best regards

**Comment by msansen-esncf** [comment]
Hi,

I don't have this bug with my admin exposed with a base_href
I only configure admin path with - botadminverticle_base_href=/bot/admin and all is rendered .

Which version are you using, it has been fixed few weeks ago.

Regards

Mat

**Comment by Houpert** [comment]
Hello,

We are using the TAG : 20.9.3
I forget to add that Tock is deployed with an edge router (traefik) on an **<host>/tock/**

Best regards

**Comment by msansen-esncf** [comment]
Hi,

#1207 is for next release 21.3
