### ISSUE TITLE
[Studio]{Sentences Dump} Not ordered after import

### ISSUE THREAD

**Issue by msansen-esncf** [theopenconversationkit/tock#1252]
Hello,

I have seen that when we load sentences from a dump from Studio, the inbox timeline is lost, the admin team like to use the inbox as a Last asked to Bot LAst in the Inbox .
Possible to keep sentences order at export /import?

seems that sentence dump loose the timestamp :
"sentences": [
        {
            "text": "text1",
            "intent": "aa:unknown",
            "entities": [
                {
                    /*---removed---*/
                }
            ],
            "language": "fr",
            "status": "inbox"
        },
        {
            "text": "text2",
            "intent": "aa:abcd",
            "entities": [
                {
                   /*---removed---*/
                }
            ],
            "language": "fr",
            "status": "inbox"
        },...

Regards

Mat

**Comment by vsct-jburet** [comment]
the sentences are sorted by last update date. When you import them, the new sentences are of course updated, so they come first. 

 I can sort the sentences exported in LIFO mode. Then, when the sentences are imported, the order will be the same than the original.

**Comment by msansen-esncf** [comment]
Hi Julien, Thank you for feature.
Just tried with latest-SNAPSHOT but order is not the same :(

Regards

Mat

**Comment by vsct-jburet** [comment]
I've made a quick test on demo platform and it seems to be ok:

1) export inbox sentences of an app
2) import sentences on other app

-> the sentences are in same order in 2) than 1)

@msansen-esncf could you check please? :)

**Comment by msansen-esncf** [comment]
Hi Julien, Thank you for feature.
Just tried with latest-SNAPSHOT **every thing is working as expected** !!!
sentences are ordered as expected

My first test failed due to an old latest SNAPSHOT on our registry...Fixed by pulling directly from docker HUB sorry for the mistake

Many thanks!!

Regards

Mat
