### ISSUE TITLE
 Analytics > Selected intents value not changing in "Message by Intent" & "Message by Story"

### ISSUE THREAD

**Issue by TonioTi** [theopenconversationkit/tock#1253]
Maybe linked with #1229 
Wichever intents are filtered on both those graphs, the lines & values stay the same. 
Only labels are changing :

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/59885647/114712250-2d5d1c80-9d30-11eb-9ba4-b6f05979b1e5.png">

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/59885647/114712388-52518f80-9d30-11eb-9043-321967329047.png">

**Comment by francoisno** [comment]
Thanks for noticing this bug/regression @TonioTi !
I have the same issue on demotock: when changing the selected intents/stories, the values are correct (legend, pie chart, CSV export) but the histogram is not correctly refreshed.

In the example below, the _Installation_ intent has been triggered once (total) yet the value for the 04-08 would be 2...
![image](https://user-images.githubusercontent.com/7584800/114741966-900fe180-9d4b-11eb-9e22-c81807449336.png)

@bakic any idea?
