### ISSUE TITLE
 entities : upper/lower case writing

### ISSUE THREAD

**Issue by edbotdemo** [theopenconversationkit/tock#1259]
There seems to be a problem regarding the recognition of entities linked to words while using different upper/lower case writing. This happens even if the word has been added in the entity’s directory beforehand. You’ll find pictures describing the issue, the word is comprehended when using lowercase while it is not when using uppercase.

![image](https://user-images.githubusercontent.com/71820900/116894939-ed080480-ac32-11eb-9502-4777eaa4046e.png)
![image](https://user-images.githubusercontent.com/71820900/116894994-fd1fe400-ac32-11eb-8fd4-5e9dfda8c24d.png)

Regards, 
Camille

**Comment by francoisno** [comment]
Hello Camille,
What is the result of lowercase _"Qu'est ce que l'Offre Mobilité individuelle ?"_ ?
What is this entity _service_, which intent is it related to (is it the same intent?) and what are the qualified values for this entity?

**Comment by vsct-jburet** [comment]
This is not a bug. "OFFRE MOBILITE INDIVIDUELLE" is not well detected by the model. You have two options:

- qualify more sentences (and then "OFFRE MOBILITE INDIVIDUELLE" will be well-detected)
- add the label MOBILITE INDIVIDUELLE in the labels of the entity value

HTH

**Comment by vsct-jburet** [comment]
The detection is performed by the nlp model. Looks like your model does not perform well. Then predefined entity values have no influence on the nlp model performance : they are used only for the evaluation of the entity.

It seems that you have no enough qualified sentences - or that the nlp model is not well configured
