### ISSUE TITLE
[Tock Studio] Ending Rule not compliant with programmatic Stories

### ISSUE THREAD

**Issue by ebrost** [theopenconversationkit/tock#1263]
When setting Ending Rules on stories in Tock Studio

Tock Studio Story ending on Tock Studio Story : OK
Tock Studio Story ending on Programatic Tock  : OK
Programatic Tock ending on story of any type : KO, only the first story is executed

**Comment by francoisno** [comment]
Hi @ebrost I can confirm Story Endings currently work only with _Configured Stories_ ie. stories, created in Tock Studio.
It might be possible to extend the feature to builtin stories... to be verified.
Any hint @vsct-jburet ?

**Comment by vsct-jburet** [comment]
yes this is WAD. Could be enhanced, though.

**Comment by vsct-jburet** [comment]
This is not that easy to implement. The code is currently in ConfiguredStoryHandler, we need to move it in a dedicated private StoryHandlerListener

**Comment by samail** [comment]
Hi @vsct-jburet, 
As discussed, we're ready to move forward on this topic as well as the transition feature.
Do you have any other recommendations to share with us in order to facilitate our start on the subject? We will check about ConfiguredStoryHandler/StoryHandlerListener too. 
Thanks

cc @amine190

**Comment by amine190** [comment]
Hello @vsct-jburet , I hope you are doing well. I ported the code concerning the stories ending rules from the ConfiguredStoryHandler handler to BotApiHandler, the idea is to open a PR to discuss the code design (I had to inject the **DAO layer** into the BotApiHandler). I hope we can schedule a call if you will be available to discuss the various difficulties I encountered during development.

Thank you,

**Comment by amine190** [comment]
@vsct-jburet, i tried to push the branch but, i d'ont have the permission

**Comment by francoisno** [comment]
Hi @amine190 could you create the PR from a branch on a fork. You can easily fork the main repository to your own personal space, then apply your mods and submit the PR from there. Please tell me in case of difficulties.

![image](https://user-images.githubusercontent.com/7584800/131317033-121203f9-2eb5-4e97-b314-298ad7be3d23.png)
