### ISSUE TITLE
Duplicated action and export unclean

### ISSUE THREAD

**Issue by edbotdemo** [theopenconversationkit/tock#1266]
While creating some stories, I duplicated Action and then modified them. 
But when exporting stories, the exports are not "clean" because they keep the creation information of the entry and don't update it.

For example for the story "Incident" I duplicated the Action "OneDrive" and its response card. I then changed the entity "OneDrive" to "SharePoint" and modified the response card. In Tock and in ED's responses, the changes are fine. But in the json export, the information is not the corresponding one in Tock.
Is there a script to update the keys to match what is entered on Tock while ensuring the coordination of Answers ?
![image](https://user-images.githubusercontent.com/71820900/118281287-5575a200-b4cd-11eb-9802-a7867b598738.png)
![image](https://user-images.githubusercontent.com/71820900/118281326-60c8cd80-b4cd-11eb-8f20-fde41c836ddf.png)
![image](https://user-images.githubusercontent.com/71820900/118281365-69b99f00-b4cd-11eb-8c1c-1fceb5157431.png)
![image](https://user-images.githubusercontent.com/71820900/118281510-92da2f80-b4cd-11eb-9432-e734b5b61c5a.png)
![image](https://user-images.githubusercontent.com/71820900/118281692-cae17280-b4cd-11eb-858b-31e97b591cf1.png)

Regards, 
Camille

**Comment by vsct-jburet** [comment]
True. The default label is copied from the first sentence and not updated after changes. It should be updated for the defaut locale.

**Comment by vsct-jburet** [comment]
The fix will only work for new changes, not old ones

**Comment by edbotdemo** [comment]
![image](https://user-images.githubusercontent.com/71820900/122527819-f8b15e00-d01b-11eb-8cf1-92c217dfb9e0.png)
![image](https://user-images.githubusercontent.com/71820900/122528220-5d6cb880-d01c-11eb-87fb-fab7200397f8.png)
![image](https://user-images.githubusercontent.com/71820900/122528693-ea177680-d01c-11eb-837c-5515c1b7f09a.png)
![image](https://user-images.githubusercontent.com/71820900/122534312-b17a9b80-d022-11eb-9097-36033f1ca242.png)

Hello, 
The modification is made only on the "defaultlabel" section. The other fields don't update after modification of response card.

Regards, 
Camille
