### ISSUE TITLE
Inbox search bar for intent qualification bug in v21.3.2

### ISSUE THREAD

**Issue by Cypres-c** [theopenconversationkit/tock#1268]
Since the v21.3.2, the search bar for intent qualification is available. 

The feature doesn't seem too work all the time.
The requalification is not updated and the Tock Studio admin keeps the first intent detected in the bar.

Example : 
![image](https://user-images.githubusercontent.com/63288353/120349598-87c13500-c2fe-11eb-9ff3-a6a3318af08f.png)
I choose here the correct intent : 
![image](https://user-images.githubusercontent.com/63288353/120350153-0322e680-c2ff-11eb-818b-524aa13d1c7d.png)
After the click the first intent found by the bot is back : 
![image](https://user-images.githubusercontent.com/63288353/120350217-12099900-c2ff-11eb-8b15-3319e18258e7.png)

**Comment by vsct-jburet** [comment]
@Cypres-c can you check that the bug is no longer reproductible on https://demo.tock.ai/nlp/inbox ?

**Comment by edbotdemo** [comment]
I see the same problem on the ED Bot demo.
Intent detection remains blocked on the same intention unless I refresh the page.

[image](https://user-images.githubusercontent.com/71820900/121160600-84710080-c84c-11eb-9f4d-ea52b99460de.png)
![image](https://user-images.githubusercontent.com/71820900/121160537-79b66b80-c84c-11eb-8ce8-66b5553de3d1.png)
![image](https://user-images.githubusercontent.com/71820900/121160664-95217680-c84c-11eb-9970-b0a8cff5e59e.png)

**Comment by Cypres-c** [comment]
After checking the demo, the bug seems to be fixed. When will it be released ?

**Comment by vsct-jburet** [comment]
I think I will release a patch at the end of the week
