### ISSUE TITLE
Tock setting to enable or disable Case sensitive

### ISSUE THREAD

**Issue by msansen-esncf** [theopenconversationkit/tock#1271]
Hi,

Our use case is a full text bot. We have troubles while detecting same words depending on the case provided: lower, upper, etc
A nice feature would be to be able to choose the case setting for the entire bot.

Regards

Mat

**Comment by francoisno** [comment]
@vsct-jburet is Tock model case-sensitivity a design choice or required? Could it be an option for each application?

**Comment by vsct-jburet** [comment]
There is not option today to be case insensitive. Could be a new feature.

**Comment by msansen-esncf** [comment]
Hi @vsct-jburet 

It would be nice if you can add this case insensitive Feature? Should i open a new issue or we can use this one
