### ISSUE TITLE
Studio INBOX: Ability to filter inbox by day 

### ISSUE THREAD

**Issue by msansen-esncf** [theopenconversationkit/tock#1289]
Hi,

coultd it be possible to add a feature to filter the inbox in the search tab by the day that the message has been send to the bot.
So for the inbox review, we would be able to do it day by day?

actual Last in First Out is nice but messages are sometime put down the list really fast and it's hard to review.

regards.

**Comment by francoisno** [comment]
Hello @msansen-esncf actually it is possible to filter sentences by day in the _Search_ tab:
- first select _Status: Inbox_ (except if you're interested in qualified sentences too, of course)
- use the _Modified after_ filter (and possibly _Modified before_ too)

Can you try and tell, if it's what you were looking for?

**Comment by msansen-esncf** [comment]
Hi, seems to be what we are looking for, how have we missed it ?!  Sorry and thanks

**Comment by NathanDitchi2** [comment]
We can close !
