### ISSUE TITLE
Bundle : correctif CSS mobile

### ISSUE THREAD

**Issue by cpicaud** [theopenconversationkit/tock#1339]
Lors de l'intégration du bundle dans un site comme SharePoint, le passage en vue mobile place la chat-box hors champ de l'utilisateur.

Le CSS semble interprété par les différents navigateurs écrasant les valeurs de margin et de position bottom+right.

L'expérience utilisateur est altéré avec un une animation inverser (ouverture qui déroule du top/left vers bottom/right au lieu de bottom/right vers top/left).

Affichage du bandeau Chattez avec le bot initialement masqué deviens visible lors de l'ouverture sous la chat-box.

![3](https://user-images.githubusercontent.com/95469993/157857960-50a8a5df-5706-47ad-bf71-715104ec5c2f.png)
![4](https://user-images.githubusercontent.com/95469993/157857962-929e0179-0e21-466e-b540-d60ce4f5fbc2.png)
![2](https://user-images.githubusercontent.com/95469993/157857965-a18cd885-8115-41a1-8633-69ce4334fd23.png)
![1](https://user-images.githubusercontent.com/95469993/157857968-5abdf10d-c67d-4fbe-8db3-d6f596cfbbb8.png)

**Comment by cpicaud** [comment]
https://github.com/theopenconversationkit/tock-react-kit/issues/101

**Comment by NathanDitchi2** [comment]
A clôturer
