### ISSUE TITLE
[Studio] fast-navigation et intention en cascade

### ISSUE THREAD

**Issue by STtesting** [theopenconversationkit/tock#1356]
**Contexte**

Dans le studio, sur une story, j'ai des actions faisant un arbre de décision : 
![image](https://user-images.githubusercontent.com/72971280/163574514-9c2df3c3-92c5-4595-90bf-3319e48db33a.png)

Lorsque l'on répond "oui", les 2 niveaux sont descendus automatiquement.

**Résultat attendu**

Si je répond oui à la première action, je ne descend que d'un niveau à la fois.

**Comment by vsct-jburet** [comment]
lié à #1172. Corrigé et inckus dans la release 22.3.0
