### ISSUE TITLE
[Tock Studio] Bug when deleting / adding an action button in a story

### ISSUE THREAD

**Issue by AdrienSNCF** [theopenconversationkit/tock#1374]
When we delete / add the action buttons in a certain order, the last one has its content deleted (title and url) at the same time a new blank action button is added.

Here is the order we noticed : 
- I have 3 actions buttons
- I delete the middle one
- I add a new action
- The last button content is deleted at the same time a new button is added

<img width="940" alt="1" src="https://user-images.githubusercontent.com/103110727/171820988-6d14621d-595d-40a1-b7c4-102ddb28c49b.png">
<img width="935" alt="2" src="https://user-images.githubusercontent.com/103110727/171820996-4a81aabe-833e-418b-97ad-bb112f23d1b6.png">
<img width="941" alt="3" src="https://user-images.githubusercontent.com/103110727/171820999-3aa82efc-a0b1-459e-af8b-102b0d989b51.png">
<img width="934" alt="4" src="https://user-images.githubusercontent.com/103110727/171821031-cca01359-8ac4-4ef8-ae5a-fbc991262601.png">

**Comment by vsct-jburet** [comment]
Thank you for reporting, fixed in next release
