### ISSUE TITLE
[Cybersécurité] : Absence de politique de verrouillage de compte

### ISSUE THREAD

**Issue by cpicaud** [theopenconversationkit/tock#1383]
Résumé : 
L’application ne possède pas de politique de verrouillage des comptes. Ainsi il est possible d’effectuer de multiples tentatives de connexion sans être bloqué. 
Plan d'action : 
Nous recommandons d’implémenter une protection contre les attaques sur les mots de passe utilisateur par énumération de façon à ce qu’un outil automatisé ou semi automatisé ne puisse être utilisé à cette fin.

**Comment by NathanDitchi2** [comment]
A clôturer
