### ISSUE TITLE
[Cybersécurité] : absence fonctionnalité changement de mot de passe

### ISSUE THREAD

**Issue by cpicaud** [theopenconversationkit/tock#1385]
Résumé : L’application n’offre pas la possibilité à ses utilisateurs de changer leur mot de passe. 
Plan d'action : Implémenter un mécanisme de changement de mot de passe dans l’espace d’administration du bot, tout en veillant à respecter la politique du groupe SNCF en matière de mot de passe.

**Comment by djowalker** [comment]
Nous avons utilisé PAC4J (https://github.com/pac4j/vertx-pac4j) : si jamais cela peut vous donner des idées. La gestion de compte et les habilitations sont cependant gérés en dehors de l'application.

**Comment by NathanDitchi2** [comment]
A clôturer
