### ISSUE TITLE
Migration from maven to gradle ?

### ISSUE THREAD

**Issue by djowalker** [theopenconversationkit/tock#1421]
Maven seems to be slow compared to Gradle builds, however it would be a breaking change for travis, and the CI/CD of everyone.

https://gradle.org/maven-vs-gradle/

**Comment by djowalker** [comment]
We will try an automatic conversion to see how it is working.
https://docs.gradle.org/current/userguide/migrating_from_maven.html#migmvn:automatic_conversion

**Comment by vsct-jburet** [comment]
Would be great. Tell us :)

**Comment by djowalker** [comment]
I started something here : https://github.com/CreditMutuelArkea/tock/tree/1427-migration-maven-to-gradle
Don't understand what i am doing but it created something.

**Comment by djowalker** [comment]
Not sure if I will continue on this.

**Comment by djowalker** [comment]
If i considered maven slow it is because I didn't know the following feature wich is used in `etc/deploy.sh` with `mvn -T threadC`
https://medium.com/blog-blog/parallel-builds-in-maven-3-bd846d22d02f
