### ISSUE TITLE
[Bug] [Tock Studio] Bugs with actions when updating the Tock version

### ISSUE THREAD

**Issue by AdrienSNCF** [theopenconversationkit/tock#1433]
Since we updated the Tock version, the actions buttons in the Media Card are not corrects. We have the same problem on the preprod and prod environment  : we have the correct number of buttons but the same text and same link on every button. It is always the text + link of the last button of the media card.
The buttons are correct when we use the bot, they are only incorrect in the backoffices

![image](https://user-images.githubusercontent.com/103110727/210402867-3dd07726-3135-4072-bc9d-91c962a0ca73.png)

![image](https://user-images.githubusercontent.com/103110727/210403335-88610c5b-0b95-4d45-88b9-1bb858c8e2e2.png)

**Comment by AdrienSNCF** [comment]
We downgraded Tock to v21.9.6 version and it came back to normal, the problem seems to be with the last version released

**Comment by correi-f** [comment]
Hope it can help to resolve this issue that can be troublesome

**Comment by AdrienSNCF** [comment]
Thanks a lot !
