### ISSUE TITLE
[RELEASE NOTE 22.3.0] [Information trouble about FAQ deletion] 2 bots same name in 2 namespaces

### ISSUE THREAD

**Issue by djowalker** [theopenconversationkit/tock#1485]
## FR 
Si l'import dans un nouveau namespace en gardant le même nom du bot, si on souhaite supprimer un des 2 bots, la suppression va supprimer les FAQ présentes dans les deux bots.

Cela s'expliquer par :

Avant de supprimer l'application (bot), on supprime les données suivantes : 

- ClassifiedSentence via `applicationId` (-> `application._id`)
- Intent via  `applicationId` (-> `application._id` )
- FAQ via `botId` (-> `application.name`) mais celui là n'est pas unique, d'où le problème de cloisonnement !

S'il faut absolument garder le botId (-> application.name ), il va falloir définir une clé unique pour les FAQ (en le couplant avec le namespace par exemple). Sinon on pourrait faire un retour arrière et n'utiliser que l'applicationId.
Cependant il faudra penser à de la migration de données vers la mise à jour du modèle de données.

## EN 
If an import occurs in a new namespace and keeping the same bot name, when trying to delete one of the 2 bots, it will delete all FAQ presents in the two bots.
 
It is explained by : 

Before deleting application, we delete the following data :
- ClassifiedSentence with applicationId
- Intent with applicationId
- FAQ with botId (application.name), however this one is not unique.

Could be interesting to add a unique key by coupling `namespace` with FAQ or just go back and use only applicationId in database for faq_definition.
However this will needs migrating existing data to updated database model for faq_defintion.

**Comment by Benvii** [comment]
Merci @djowalker, coté TOCK @vsct-jburet est-il possible de référencer cette limitation idéalement sous forme d'une release note ?

On a eu le cas coté CM Arkéa, copie de bot sur un autre namespace pour le tester / debug puis suppression qui a entraîné la suppression des FAQ.

**Comment by djowalker** [comment]
fixed with #1522
