### ISSUE TITLE
[Messenger Connector] Tock does not handle proxy authentication

### ISSUE THREAD

**Issue by Fabilin** [theopenconversationkit/tock#1493]
When attempting to use the Messenger connector behind a proxy that requires basic authentication, we get the following error:
```
ERROR [vert.x-worker-thread-4] a.t.b.c.m.MessengerClient [Retrofits.kt:347] <-- HTTP FAILED: java.io.IOException: Failed to authenticate with proxy
WARN [vert.x-worker-thread-4] a.t.b.c.m.MessengerClient [MessengerClient.kt:285] {<redacted>,"messaging_type":"RESPONSE","notification_type":"NO_PUSH"}
ERROR [vert.x-worker-thread-4] a.t.b.c.m.MessengerConnector [Loggers.kt:24] Failed to authenticate with proxy
ai.tock.bot.connector.ConnectorException: Failed to authenticate with proxy
        at ai.tock.bot.connector.messenger.MessengerClient.throwError(MessengerClient.kt:291)
        at ai.tock.bot.connector.messenger.MessengerClient.send(MessengerClient.kt:328)
        at ai.tock.bot.connector.messenger.MessengerClient.send(MessengerClient.kt:278)
        at ai.tock.bot.connector.messenger.MessengerClient.sendMessage(MessengerClient.kt:172)
        at ai.tock.bot.connector.messenger.MessengerConnector.sendEvent(MessengerConnector.kt:285)
        at ai.tock.bot.connector.messenger.MessengerConnector$send$2.invoke(MessengerConnector.kt:430)
        at ai.tock.bot.connector.messenger.MessengerConnector$send$2.invoke(MessengerConnector.kt:429)
        at ai.tock.bot.connector.ConnectorQueue.sendActionFromConnector(ConnectorQueue.kt:78)
        at ai.tock.bot.connector.ConnectorQueue.access$sendActionFromConnector(ConnectorQueue.kt:30)
        at ai.tock.bot.connector.ConnectorQueue$add$1.invoke(ConnectorQueue.kt:64)
        at ai.tock.bot.connector.ConnectorQueue$add$1.invoke(ConnectorQueue.kt:63)
```

## Proposed solution

I believe the simplest fix would be to update the following code to call `proxyAuthenticator(okhttp3.Authenticator.JAVA_NET_AUTHENTICATOR)`:
https://github.com/theopenconversationkit/tock/blob/dfa310d0d612775c381948d50b1fe8e600fe20bc/shared/src/main/kotlin/Retrofits.kt#L99-L104
This would allow applications to globally set a default authenticator at startup and have it be picked up by TOCK calls.

**Comment by djowalker** [comment]
I believe in `MessengerClient.kt` the proxy parameter is still null because in Retrofit.kt

```
fun retrofitBuilderWithTimeoutAndLogger(
    ms: Long,
    logger: KLogger = KotlinLogging.logger {},
    level: Level = retrofitLogLevel(retrofitDefaultLogLevel),
    interceptors: List<Interceptor> = emptyList(),
    /**
     * Gzip the request for servers that support it.
     */
    requestGZipEncoding: Boolean = false,
    /**
     * Add a circuit breaker facility.
     */
    circuitBreaker: Boolean = false,
-->HERE    proxy: Proxy? = null
): 
```

On another project i used the following idea :  

```
import java.net.InetSocketAddress
import java.net.Proxy

object ProxyConfiguration {

    /**
     * Configure proxy
     * @param proxyHost : host
     * @param proxyPort : port
     */
    fun configure(proxyHost: String, proxyPort: Int): Proxy {
        return if (proxyHost.isNotBlank()) {
            val address = InetSocketAddress(proxyHost, proxyPort)
            Proxy(Proxy.Type.HTTP, address)
        } else {
            Proxy.NO_PROXY
        }
    }
}
```

So when using a RetrofitClient.kt like in MessengerClient.kt, for instance with properties :
```

    val proxyPort = intProperty("tock_messenger_api_proxy_port", 3128)
    val proxyHost = property("tock_messenger_api_proxy_host", "")
(...)

//same on statusApi ?
graphApi = retrofitBuilderWithTimeoutAndLogger(
            longProperty("tock_messenger_request_timeout_ms", 30000),
            logger,
            requestGZipEncoding = booleanProperty("tock_messenger_request_gzip", true)
            //proxy loaded if proxyHost assigned
            proxy = 
   proxy = ProxyConfiguration.configure(
                   proxyPort,
                   proxyHost
                )
        )
(...)
```
Or you idea is to use the java proxy directly

**Comment by Fabilin** [comment]
Right, we really have three options to configure the proxy here:

1. Use TOCK-specific environment properties for host, port, user, password
   - Pros: requires no code to use
   - Cons: requires configuring TOCK separately from everything else
2. Add a generic callback (in e.g. [`BotRepository`](https://github.com/theopenconversationkit/tock/blob/dfa310d0d612775c381948d50b1fe8e600fe20bc/bot/engine/src/main/kotlin/engine/BotRepository.kt)) that allows apps to configure the [OkHttp builder](https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html) before building a retrofit object
    - Pros: flexible, can be used for more than proxy configuration
    - Cons: requires code to use, requires configuring TOCK separately from everything else
3. Use the global [`ProxySelector`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/ProxySelector.html) and [`Authenticator`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/Authenticator.html)
    - Pros: standardized solution, shares configuration with every other library
    - Cons: requires code to use, cannot benefit from OkHttp optimizations like preemptive authentication

**Comment by vsct-jburet** [comment]
Tock uses Retrofit to make requests to messengers or other partners. Retrofit supports the java proxy properties: 

https://www.baeldung.com/java-connect-via-proxy-server

So not sure to understand why there is a need for a PR ?

**Comment by Fabilin** [comment]
That's right, it uses the java proxy properties through the global ProxySelector. However, as far as I am aware, you have to configure an Authenticator to go through an authenticated proxy - hence the "Failed to authenticate with proxy" error in my stacktrace.

**Comment by vsct-jburet** [comment]
The properties

```
http.proxyUser
http.proxyPassword
https.proxyUser
https.proxyPassword
```

do not work ?

**Comment by Fabilin** [comment]
I have had no luck setting those, and I have seen no mention of them in the JDK or official documentation either. I may be mistaken, but it seems those properties are only used by select libraries like Apache HTTP client.

**Comment by vsct-jburet** [comment]
Yes it seems to be non-standard properties :(

I would like to go to the 1) : 

Use TOCK-specific environment properties for host, port, user, password

-> this is the simplest way to implement the feature I think

HTH

**Comment by Fabilin** [comment]
Sounds good to me, although after some thinking I think this idea can be simplified.

First, should we actually set the proxy host and port from environment properties, or should we keep relying on the JDK's ProxySelector? The only reason I can see for changing the current behaviour in that regard is that the proxy selector could possibly yield a proxy that does not match the given credentials, but I believe that to be fairly inconsequential. Setting the proxy ourselves could also cause issues by disregarding the nonProxyHosts property.

 Then, should we actually use TOCK-specific properties like `tock_proxy_user` and `tock_proxy_password`, or the semi-standard ones `http.proxyUser` and `http.proxyPassword`? Using our own properties could allow for independant configuration and maybe more importantly allow configuration through environment variables (system properties being more unwieldy in some environments). On the other hand, relying on the semi-standard ones could save the user some time as many applications already set those.
