### ISSUE TITLE
OAuth 2.0 with Keycloak?

### ISSUE THREAD

**Issue by DylanCLINCHAMP** [theopenconversationkit/tock#1501]
Hi everyone, I'm trying to use OAuth2 to manager users with Keycloak. My issue is that when a user logs in, he gets redirected to keycloak as expected and can log in. Then when the callback to Tock is triggered, the user gets "Internal Server Error" and the tock-admin containers reports an exception in Oauth2Provider ("java.lang.NullPointerException: user.get<String>("id_token") must not be null"). Has anyone experienced issues with Tock OAuth2?
[Stack trace tock login OAuth 2.0.txt](https://github.com/theopenconversationkit/tock/files/11834045/Stack.trace.tock.login.OAuth.2.0.txt)

**Comment by djowalker** [comment]
The trouble seems to happen here : https://github.com/theopenconversationkit/tock/blob/master/shared/src/main/kotlin/security/auth/OAuth2Provider.kt#L114

However i did not used Oauth2Provider.
But in what I saw here as an example : the id_token would be like the presented one here : https://www.oauth.com/oauth2-servers/signing-in-with-google/getting-an-id-token/

However is it properly filled with the callback ?
In the kotlin file (OAuth2Provider.kt) there are also some properties maybe you already tried to use some of them ?

**Comment by DylanCLINCHAMP** [comment]
Hi, thanks for the insight. It seems that it does not find "email" (L113) before trying the "id_token". I've checked with postman and there seems to be an email in the userinfo. Nether the less, I added the "id_token" scope to my client in Keycloak (a fake on for testing). I can see it with Postman but Tock still does not find it.
Here are the configuration values I set in my Dockerfile:
(I’ve hidden the real domain name and the Keycloak secrets)

- tock_oauth2_enabled=true
- tock_oauth2_client_id=tocktest
- tock_oauth2_secret_key=thesecretkeyprovidedbykeycloak
- tock_oauth2_site_url=https://sso.mydomain.fr
- tock_oauth2_access_token_path=https://sso.mydomain.fr/realms/myrealmfortock/protocol/openid-connect/token
- tock_oauth2_authorize_path=https://sso.mydomain.fr/realms/myrealmfortock/protocol/openid-connect/auth
- tock_oauth2_userinfo_path=https://sso.mydomain.fr/realms/myrealmfortock/protocol/openid-connect/userinfo
- tock_oauth2_user_role_attribute=tock_roles

I used the paths provided by Keycloak at https://sso.mydomain.fr/realms/myrealmfortock/.well-known/openid-configuration.

When testing with postman by requesting an authorization token and then the userinfo, here are the values that get returned:
https://sso.mydomain.fr/realms/myrealmfortock/protocol/openid-connect/userinfo
{
    "sub": "834b57d0-e909-492a-a08d-017428213fd4",
    "email_verified": true,
    "id_token": "aaaaaaaaaaaaaaaaaaaavbvv",
    "preferred_username": "admin@app.com",
    "given_name": "",
    "family_name": "",
    "email": "admin@app.com"
}

I wonder if Tock is expecting to get "email" or "id_token" in the user itself because if it got to lines 113 and 114, it means that an "access_token" has been found in the user at line 111. The "email" and "id_token" are encoded into the "access_token" so maybe they are not appearing in the user itself.

Here is the data in the decoded access_token:
{
  "alg": "RS256",
  "typ": "JWT",
  "kid": "pUHT5Kl5qzRd8rIDIXYNbKAdUy40l282EGDT54XD6Po"
}.{
  "exp": 1687505470,
  "iat": 1687505170,
  "auth_time": 1687504117,
  "jti": "e0f455aa-683f-42e1-b84c-5315496bfd01",
  "iss": "https://sso.mydomain.fr/realms/myrealmfortock",
  "aud": "account",
  "sub": "834b57d0-e909-492a-a08d-017428213fd4",
  "typ": "Bearer",
  "azp": "tocktest",
  "session_state": "2af0b346-690f-4453-bd8b-4dd4a9bbaaa1",
  "acr": "1",
  "allowed-origins": [
    "https://admin-test-tock.mydomain.fr"
  ],
  "realm_access": {
    "roles": [
      "offline_access",
      "id_token",
      "default-roles-myrealmfortock",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "tocktest": {
      "roles": [
        "id_token",
        "tock_roles"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "openid profile email id_token",
  "sid": "2af0b346-690f-4453-bd8b-4dd4a9bbaaa1",
  "email_verified": true,
  "id_token": "aaaaaaaaaaaaaaaaaaaavbvv",
  "preferred_username": "admin@app.com",
  "given_name": "",
  "family_name": "",
  "email": "admin@app.com"
}.[Signature]

**Comment by djowalker** [comment]
Just asking : is it normal that the mail indicated is the default one on Tock ? "admin@app.com ?
On the other maybe you can check if you need to used everytihin that is provided with Oauth2Provider, the GithubOauthProvider is a more simpler example, maybe it is interesting to create a specific : KeycloakOauthProvider and it a way to contribute to Tock

**Comment by DylanCLINCHAMP** [comment]
Hi, yes, it is. We created a mock account on Keycloak using that e-mail (we wanted to see if a user from Keycloak with the same e-mail would get access to the data added by the default user before adding the connection via Keycloak). I will try to launch Tock without using the Docker images so that I can edit and hopefully debug the Oauth2Provider for use with Keycloak.
