### ISSUE TITLE
Can't access user guide in documentation

### ISSUE THREAD

**Issue by rajp152k** [theopenconversationkit/tock#1508]
[http://doc.tock.ai/tock/en/guide/toc](http://doc.tock.ai/tock/en/guide/toc)
(the detailed user guide referred to in the manual)
throws a 404..

**Comment by djowalker** [comment]
https://doc.tock.ai/tock/en/toc/ ? 

It is the overview actually.
From which page do you clicked from? It looks like the link on messenger page is indeed wrong. We should fix that link.
At the bottom of this page it seems ok.

**Comment by vsct-jburet** [comment]
Thank you !
