### ISSUE TITLE
[Tock Studio] Fix empty namespace not appearing as selected

### ISSUE THREAD

**Issue by DylanCLINCHAMP** [theopenconversationkit/tock#1510]
Hi,
With a fresh install, the checkbox does not appear as selected until an application is creating inside that namespace (at http://[tock admin domain]/configuration/namespaces ). That issue occurs both with the default namespace and with "manually" created namespaces while they're empty (first and second screenshots). Once we create an application in that namespace, the checkbox appears as selected (third screenshot).

![Default namespace](https://github.com/theopenconversationkit/tock/assets/94701258/6ec695cb-5abb-41fd-94dd-a1037d3dc36e)
![two empty namespaces](https://github.com/theopenconversationkit/tock/assets/94701258/22690621-0ad5-4361-b275-321932ad4626)

![oneapp namespace](https://github.com/theopenconversationkit/tock/assets/94701258/96a308aa-2ffa-4c29-b3ea-59e43aebdf29)

**Comment by rkuffer** [comment]
Fixed by https://github.com/theopenconversationkit/tock/pull/1547
