### ISSUE TITLE
[Messenger] Messenger connector is not compliant with last Facebook API

### ISSUE THREAD

**Issue by ebsmarttribune** [theopenconversationkit/tock#1520]
Current version of the messenger connector is not compliant with latest Facebook API (v17.0).
When creating a new application on facebook developer console , you can't choose an older version of the API and are restricted to the latest version . Messenger connector is not working with api version above v14.0

**Comment by francoisno** [comment]
Currently the Tock connector for Messenger is built for the Facebook API version `5.0` (end 2019): see https://github.com/theopenconversationkit/tock/blob/master/bot/connector-messenger/src/main/kotlin/MessengerClient.kt#L62

The FB API is regularly updated and, when a version gets deprecated then expires, clients are automatically switched to the next API version. This way, chatbots built with the connector for `5.0` actually consume the `14.0` in production without any known problem.

The `14.0` API will expire next september the 17th according to https://developers.facebook.com/docs/graph-api/changelog/versions. This means, we have to upgrade the connector to version `15.0` or above (not compatible anymore) before the 09/17/24.

**Comment by pi-2r** [comment]
MR: https://github.com/theopenconversationkit/tock/pull/1669
