### ISSUE TITLE
[Tock] [Carousel] Is it functional?

### ISSUE THREAD

**Issue by NathanDitchi2** [theopenconversationkit/tock#1525]
Hello,

We want to know if the functionality to add a carousel works from tock ?

<img width="490" alt="Carousel1" src="https://github.com/theopenconversationkit/tock/assets/135221335/1594f2e8-0c3a-4e70-8c21-22772664e4a4">

After performing some tests (with a web connector), we are unable to display responses as a carousel, when there are several answers.

<img width="516" alt="2" src="https://github.com/theopenconversationkit/tock/assets/135221335/8ca53ac8-ead7-47e5-b710-b5925006f597">

Is it possible to tell us how this feature works ? And at the same time, how to implement it on a web connector ? We also want to implement it on a "SharePoint" type connector in the future if it's possible.

I look forward to hearing from you !
Thank you !
Nathan

**Comment by vsct-jburet** [comment]
Sorry for the late response. A carrousel is displayed when you have two or more answers with cards - not two or more actions ;) :

![image](https://github.com/theopenconversationkit/tock/assets/12413454/4fabc31f-c04b-4aea-846b-28e5d55363cc)

For the sharepoint topic, let's discuss it on gitter : https://app.gitter.im/#/room/#tockchat_Lobby:gitter.im
