### ISSUE TITLE
[Tock Studio] Media dialog modal not closed on submit

### ISSUE THREAD

**Issue by rkuffer** [theopenconversationkit/tock#1527]
The media card dialog is not closed as expected after submission

**Comment by vsct-jburet** [comment]
@rkuffer I do not reproduce the bug. Do you reproduce it on https://demo.tock.ai/ ?

**Comment by rkuffer** [comment]
@vsct-jburet Not anymore as it has been fixed by https://github.com/theopenconversationkit/tock/pull/1529

**Comment by rkuffer** [comment]
Fixed by https://github.com/theopenconversationkit/tock/pull/1529
