### ISSUE TITLE
Test Bot is giving "technical error :( ]" error on demo

### ISSUE THREAD

**Issue by sanjaykare** [theopenconversationkit/tock#1567]
I tried to click on Try It --> Try live demo link click and open https://demo.tock.ai/. I enter the story same as on YouTube demo https://www.youtube.com/watch?v=UsKkpYL7Hto

but when click Test and Enter "greetings" it gives the error message "technical error :( ]"
![image](https://github.com/theopenconversationkit/tock/assets/107122417/d5622e0f-31e7-4ff7-95c0-8631a8e0a502)

Please help on it. why it's giving error.

**Comment by vsct-jburet** [comment]
There is an issue on this platfom. We work on it. Workaround: use the docker images at  https://github.com/theopenconversationkit/tock-docker

**Comment by sanjaykare** [comment]
working with docker. thank you!
