### ISSUE TITLE
Scenarios Management menu is not visible

### ISSUE THREAD

**Issue by sanjaykare** [theopenconversationkit/tock#1569]
I installed tock from docker from https://github.com/theopenconversationkit/tock-docker & run the docker command "**Run the Bot API stack: docker-compose-bot.yml**", Login from admin everything is working fine but one menu "Scenarios Management" is not visible. Please guide me, how can I visible "Scenarios Management" menu?
![Screenshot from 2024-01-12 16-34-56](https://github.com/theopenconversationkit/tock/assets/107122417/0eed6248-b1a3-4081-ba14-ef9ccfd93457)

**Comment by stalina** [comment]
Hello,

Scenario are "stories" in tock : https://doc.tock.ai/tock/fr/user/concepts/#sc%C3%A9nario-ou-story

**Comment by rkuffer** [comment]
If you're talking about the new Scenario management feature, it hasn't yet joined the repo : https://github.com/theopenconversationkit/tock/pull/1483

**Comment by rkuffer** [comment]
Development of this feature has been abandoned. Resources have been entirely redirected towards AI generative features.
