### ISSUE TITLE
[CAS] pac4j upgrade to 6.0.1 breaking changes (CasClient & Config.sessionStore)

### ISSUE THREAD

**Issue by Benvii** [theopenconversationkit/tock#1588]
Hi Tock community,
Since the upgrade from pac4j `5.7.0` to `6.0.1` several stuff were deprecated and removed Tock full build is now broken : 
```
Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.9.21:compile (compile) on project tock-cas-arkea: Compilation failure
[ERROR] /builds/innovation/di01/tock/bot/tock-auth-cas-arkea/src/main/kotlin/security/auth/cas/ArkeaCASAuthProvider.kt:[64,19] Unresolved reference: sessionStore
```

Release not indicate that this sessionStore was replaced by a factory  see here https://github.com/pac4j/pac4j/commit/4e47b72c8e15aa8d7209fe3bac69a1b7e0fc6e37 

I also noticed that CasClient is deprecated in 5.7.0 (see this commit : https://github.com/pac4j/pac4j/commit/a9e54c86bedab6cad6d8c7e31f5e563803d047b4#diff-114223e6d33f133687c5be56642c286ee1f74a8975e8f09507be724da6be7594R20 ) and moved to `pac4j-cas-clientv4` which then disappear in 6.0.0.

I will read the entire release notes and make a clean update, adding it to CM Arkea backlog.

_Arkea's internal ref : DERCBOT-912._

**Comment by assouktim** [comment]
On Tock, to perform authentication with the CAS protocol, we use the following two pac4j libs: pac4j-core (v6.0.1) and vertx-pac4j (v6.0.2)
vertx-pac4j uses vertx-core, which has undergone huge changes, but vertx-pac4j has not kept up.

**What is blocking :** 
In pac4j-vertx, to create the io.vertx.ext.web.handler.AuthenticationHandler, we use the org.pac4j.vertx.handler.impl.SecurityHandler implementation.
This class launches the following method in static: 
static {
    Config.defaultProfileManagerFactory("VertxProfileManager", (ctx, store) -> {
        return new VertxProfileManager((VertxWebContext)ctx, (VertxSessionStore)store);
    });
} 
Except that org.pac4j.core.config.Config.defaultProfileManagerFactory no longer exists in core as of v6. 

// logs : java.lang.NoSuchMethodError: 'void org.pac4j.core.config.Config.defaultProfileManagerFactory(java.lang.String, org.pac4j.core.profile.factory.ProfileManagerFactory)' 

So, as long as the vertx-pac4j lib hasn't been updated with the core changes, we should stick with **pac4j-core: 5.7.3**

**Comment by Benvii** [comment]
Change to be made : https://github.com/pac4j/pac4j/commit/4e47b72c8e15aa8d7209fe3bac69a1b7e0fc6e37
