### ISSUE TITLE
mark incorrect answers

### ISSUE THREAD

**Issue by 1bugjian** [theopenconversationkit/tock#1594]
If I find that some answers are incorrect while using the AI Q&A assistant, how should I mark it?

**Comment by rkuffer** [comment]
If, when talking about "AI Q&A assistant", you mention the new RAG functionality, you have several options for dealing with unsatisfactory answers: 
- If the question asked is outside the bot's scope, you can exclude a question from the Rag via the Rag exclude function. An excluded Rag sentence will not trigger an Llm response attempt and will redirect to the Unknow story the next time it is asked. 
![takc-rag-exclude](https://github.com/theopenconversationkit/tock/assets/101799433/bace0793-0744-4237-ad55-04b8e401b2c2)

- If you want to offer a pre-defined answer to the question posed, create a trained story for the question, trained with the question. This will enable you to provide the precise answer you want to offer the end-user. Faq-type stories are particularly well-suited to this type of need. The next time this question is asked, the intent will be detected and the pre-defined answer will be returned to the user, avoiding the need to try to answer it via the Llm.
- If you wish to play with the answer provided by your Llm, you'll need to work on the Rag sources used (correcting erroneous information in the sources, adding a source specifically answering the question asked...).

**Comment by rkuffer** [comment]
To monitor generative AI responses, use the possibilities offered by Langfuse (in Tock Studio: Gen AI > Observability settings). A feature for monitoring Rag responses directly integrated into Tock Studio is currently being studied.
