### ISSUE TITLE
[Bot API] Locale cannot be updated from within a story handler

### ISSUE THREAD

**Issue by Fabilin** [theopenconversationkit/tock#1662]
A somewhat common request in a multilingual bot is for the bot to "switch language", where the user expects the bot to start talking in the language of their choice. As far as I know, the typical way to perform this operation is to set the user's locale as follows:
```kt
userTimeline.userPreferences.locale = locale
```
However this change is only taken into account the next time a `TockBotBus` is created, which means the answer to the "switch language" intent is improperly translated:
<img width="1004" alt="image" src="https://github.com/theopenconversationkit/tock/assets/79657435/07ae6b5f-d084-442b-b1f3-cf78147f7506">

A simple fix for this would be to make the `BotBus#userLocale` field mutable, and add a way to simultaneously set the locale in both the bus and the UserPreferences.

**Comment by vsct-jburet** [comment]
why not using bus#userPreferences.locale ? Is this solving the issue ?

**Comment by vsct-jburet** [comment]
I would say that the best fix would be to change in TockBotBus

`override val userLocale: Locale =`

by 

`override val userLocale: Locale get() =`

This is already done in BotBusMock, and I think perf cost is ok
