### ISSUE TITLE
[GenAI tooling] use trust_env aiohttp in smart_tribune_consumer.py

### ISSUE THREAD

**Issue by morgandiverrez** [theopenconversationkit/tock#1703]
no more use request for catch proxy in this script, and use trust_env=True in aiohttp

**Comment by Benvii** [comment]
Hi @morgandiverrez, 
Can you initiate a pull request is the branch https://github.com/CreditMutuelArkea/tock/tree/1703-genai-tooling-use-trust_env-aiohttp-in-smart_tribune_consumerpy the right one ?

Thanks :)
