### ISSUE TITLE
use kotlin multi platform for bot API

### ISSUE THREAD

**Issue by vsct-jburet** [theopenconversationkit/tock#171]

**Comment by vsct-jburet** [comment]
this implies using the [Kotlin multiplatform](https://kotlinlang.org/docs/reference/whatsnew12.html#multiplatform-projects-experimental) feature for messenger/ga connectors

**Comment by vsct-jburet** [comment]
a node wrapper will be available mid-october. kotlin multiplaform is targeted for 20.3

**Comment by francoisno** [comment]
Bot-Api and Tock-Node available -> issue resolved @vsct-jburet ?
