### ISSUE TITLE
Add the possibility to override okhttp default log level

### ISSUE THREAD

**Issue by sebabarre** [theopenconversationkit/tock#439]
tock should offer the possibility to override the default log level of nlpApi's HttpLoggingInterceptor (which is currently set to BODY), to clean up logs of bots, with a customable property.

I can do it if it is ok with you @vsct-jburet

**Comment by vsct-jburet** [comment]
You can already do this with level parameter of retrofitBuilderWithTimeoutAndLogger
( https://github.com/voyages-sncf-technologies/tock/blob/master/shared/src/main/kotlin/Retrofits.kt#L73 ) 
Or am I wrong? ;)

**Comment by sebabarre** [comment]
Ok, so for my understanding i can overwrite okhttp log level in case of use of this retrofit builder (like in [TeamsClient ](https://github.com/voyages-sncf-technologies/tock/blob/master/bot/connector-teams/src/main/kotlin/TeamsClient.kt#L52) by example), but how can i change the log level of api /nlp without modify https://github.com/voyages-sncf-technologies/tock/blob/master/nlp/api/client/src/main/kotlin/fr/vsct/tock/nlp/api/client/TockNlpClient.kt#L80 ?

**Comment by vsct-jburet** [comment]
You can use the tock_retrofit_log_level property ;) 

val retrofitDefaultLogLevel = propertyOrNull("tock_retrofit_log_level")
