### ISSUE TITLE
[Bot API] newStory should create the intent when necessary

### ISSUE THREAD

**Issue by francoisno** [theopenconversationkit/tock#533]
Using 'newStory' (Bot API), the intent should be created in NLU when it does not exist.
Current situation : no intent visible in NLU tabs, yet the intent name appears when editing the Story (Build).

**Comment by vsct-jburet** [comment]
fixed

**Comment by francoisno** [comment]
TODO : create intent when it does not exist, probably in `createBuiltInStoriesIfNotExist`

**Comment by francoisno** [comment]
Hello @vsct-jburet, pour créer l'intention lorsque les builtin stories sont créées, le meilleur endroit me paraît `BotRepository#registerBuiltInStoryDefinitions` (dans `tock-bot-engine`).

Côté Admin, cela se fait via `AdminService` -> `FrontClient`.
Problème : dans `tock-bot-engine` pas de dépendance vers `FrontClient` pour le moment.

2 possibilités : 
- Ajouter une dépendance à `nlp-front-client` + `nlp-front-ioc`
- Ajouter une méthode à `NlpClient` car la dépendance `nlp-api-client` est déjà là (et il y a bien `NlpClient#createApplication` dans le même genre)

 Je ne suis pas sûr des responsabilités de ces deux "clients NLP" peux-tu me dire ce qui te paraît le mieux ?

(Par ailleurs, un module "bot-front-client" ou "xxx-admin-client" serait pas mal pour mutualiser avec l'Admin les règles de gestion lorsque Bot-Api crée des stories, qu'on applique les story rules, etc.)

**Comment by francoisno** [comment]
Bon finalement j'ai ajouté `FrontClient` dans `tock-bot-api-server` - les autres solutions étaient casse-tête en pratique.

**Comment by djowalker** [comment]
@vsct-jburet @francoisno It seems that the intent are not created when loading the bot api Bot, for the stories it seems ok.
