### ISSUE TITLE
[Admin][Build] Wrong error level logging

### ISSUE THREAD

**Issue by delphes99** [theopenconversationkit/tock#548]
During mvn clean build, a npm install is launch.

The outputs of npm are logged as error

```
[ERROR] npm info it worked if it ends with ok
[ERROR] npm info using npm@6.4.1
[ERROR] npm info using node@v8.12.0
....
[ERROR] npm timing npm Completed in 109554ms
[ERROR] npm info ok 
```

**Comment by francoisno** [comment]
Thanks for noticing the build errors and submitting the issue.
This has been solved by upgrading the front-maven-plugin (from 1.7.6 to 1.8.x) : npm output is now logged as INFO.
