### ISSUE TITLE
Non suppression de phrases dans les menus inbox, unknown et search

### ISSUE THREAD

**Issue by MorganeAbadie** [theopenconversationkit/tock#732]
**Description** : Lorsque l'on est en mode tableau dans les menus inbox, unknown et search, et que sont sélectionnées des phrases à supprimer, aucune suppression n'a lieu, Les phrases sont simplement mélangées.

**Repoduction de l'anomalie** :

- être dans le menu NLU > inbox / search / unknoxn,

- mettre l'affichage en mode tableau
- sélectionner une phrase

![72062062-58f48a00-32d7-11ea-9190-457c70fc92d6](https://user-images.githubusercontent.com/54838256/72158500-aa297a00-33ba-11ea-8931-1fdcdc59940b.jpg)

**Résultats** : les phrases sont mélangées mais non supprimées

![72062069-5abe4d80-32d7-11ea-9932-e614875f4385](https://user-images.githubusercontent.com/54838256/72158519-b6153c00-33ba-11ea-9a35-f569e08ff72c.jpg)

**Comment by francoisno** [comment]
Bonjour @MorganeAbadie ,

Malheureusement je n'arrive pas à reproduire ce problème. J'ai testé les deux cas suivants :
- vue Unknown sur demo.tock.ai
- vue Inbox avec Tock en local

Est-ce que tu as toujours le problème ? Seulement sur votre installation de Tock ou bien aussi demo.tock.ai ?

Merci.
François

**Comment by MorganeAbadie** [comment]
Bonjour François,

J'ai fait une vidéo où on peut voir le souci sur les 3 onglets mentionnés (soit il ne se passe rien, soit les phrases sont mélangées à la place d'être supprimées).
Nous le retrouvons à la fois sur notre installation et sur la démo. Le vidéo a d'ailleurs été faite sur la demo.

Il semblerait que je ne puisse pas charger de vidéo ici, aurais-tu une adresse email où je pourrais te l'envoyer ?

Merci,
Morgane

**Comment by francoisno** [comment]
Bonjour @MorganeAbadie,
Tu peux essayer de m'envoyer le fichier sur mon mail pro, ou le déposer en ligne par exemple avec un service gratuit (et logiciel libre) comme https://framadrop.org/ puis m'envoyer le lien.

**Comment by LiviaHaulot** [comment]
Le problème est résolu grâce à une montée de version de Mozilla Firefox.
