### ISSUE TITLE
Problème Affichage Responsive Tock Studio

### ISSUE THREAD

**Issue by MorganeAbadie** [theopenconversationkit/tock#733]
Bonjour,

Je vous contacte car j'ai identifié 2 problèmes d'affichage sur Tock Studio.
Tout d'abord:
- NLU > Intents
La colonne de l'intent s'adapte à la longueur de l'intent mais lorsqu'il est trop long, la colonne est trop grande, cela décale les colonnes suivantes et une partie de la colonne Actions est hors champs.
Nous ne pouvons le cas ci-dessous plus accéder au bouton Delete.

![ano_responsive_nlu](https://user-images.githubusercontent.com/54838256/72082757-f1533480-3300-11ea-8ec3-e38fbf0b8dfe.PNG)

- Build >Story > Create a New Story
Lorqu'on est sur un écran trop petit, la partie basse de la pop-in est cachée et nous ne pouvons pas valider la création de la story.

![ano_responsive_build](https://user-images.githubusercontent.com/54838256/72082911-3c6d4780-3301-11ea-9c43-1a7dd7b21693.PNG)

Merci d'avance pour votre aide.

Morgane

**Comment by francoisno** [comment]
Bonjour Morgane,
Je viens de pousser une Pull Request avec différentes adaptations pour corriger ces problèmes :
- Ellipse des noms et ID d'intentions au-delà d'une certaine largeur (ie. coupe le mot avec ... à la fin)
- Les libellés des deux boutons "Add" deviennent des tooltips uniquement
- En cas de manque de place les actions (boutons de la dernières colonne) se mettront les uns sous les autres
- La modale de création de Story sera maintenant limitée à la partie visible de la page, et surtout scrollable

Il reste à faire les reviews et intégrer ça dans une release Tock, mais d'ici là à titre de contournement : quand tu es bloquée et ne vois pas certains composants, tu peux probablement utiliser CTRL+Molette bas pour réduire le zoom de la page, ça devrait te permettre de voir tous les boutons quelque soit la taille de ton écran.

**Comment by MorganeAbadie** [comment]
Bonjour François,

Je te remercie pour la prise en compte de ces anomalies et les corrections proposées me paraissent convenir.
Oui effectivement en dézoomant la page, nous parvenons à accéder aux différents boutons. Nous ferons comme ça d'ici la prochaine release.
As-tu d'ailleurs une date à nous communiquer et des infos quant aux fonctionnalités qu'elle embarquera ?

Merci et bonne journée.
Morgane

**Comment by francoisno** [comment]
Bonjour @MorganeAbadie ,
Merci pour ton retour. La prochaine release 19.9.3 ne devrait pas tarder, probablement en fin de semaine. Tu peux voir les tickets qui sont taggés 19.9.3 pour avoir une idée du contenu : https://github.com/theopenconversationkit/tock/issues?q=is%3Aopen+is%3Aissue+milestone%3A19.9.3
Bonne journée,
François

**Comment by MorganeAbadie** [comment]
Bonjour François,

Je vois que le ticket est fermé mais nous n'avons pas vu la release sur Docker Hub.
Peux-tu me donner de la visibilité pour qu'on prévoie la montée de version de notre côté ?

Merci et bonne fin de journée,
Morgane

**Comment by vsct-jburet** [comment]
@MorganeAbadie  à priori le correctif est disponible sur https://demo.tock.ai
Peux-tu confirmer que le problème est bien corrigé? Si c'est bien le cas la release de la prochaine version est prévue pour mercredi ou jeudi.

**Comment by MorganeAbadie** [comment]
Bonjour Julien,

Je te confirme que la correction est bien effective sur demo.tock.ai. Il en est de même pour le ticket 734.
Nous attendons donc la release de cette semaine :)

Merci.
