### ISSUE TITLE
Other Intent probabilities

### ISSUE THREAD

**Issue by MorganeAbadie** [theopenconversationkit/tock#734]
Bonjour,

Nous avons constaté une régression sur la nouvelle version de Tock.
NLU > Inbox
Lorsqu'une phrase est associée à un intent avec une probabilité relativement faible, auparavant, nous avions la possibilité d'accéder directement aux autres intents et probabilités avec lesquels le modèle avait hésité.
Ce n'est maintenant plus le cas, nous n'avons plus accès aux autres intents depuis cet endroit de l'admin.

![other_intent_probabilities](https://user-images.githubusercontent.com/54838256/72144722-43e02f80-3399-11ea-93c7-2f26b2f51706.PNG)

Merci par avance pour votre aide.

Morgane

**Comment by vsct-jburet** [comment]
@MorganeAbadie j'ai bien le bouton sur la plateforme de démo. Merci de vérifier dans les logs nlp que la propriété "otherIntentsProbabilities" est non vide.

![image](https://user-images.githubusercontent.com/12413454/72388825-34f5d600-3727-11ea-8f41-5982e2cc8363.png)

--

![image](https://user-images.githubusercontent.com/12413454/72388800-25768d00-3727-11ea-8d6a-36d4e7f40fd9.png)

**Comment by MorganeAbadie** [comment]
Bonjour Julien,

Il y a bien des informations dans les logs.
Voici ce que j'ai pour l'exemple donné dans le premier message :
Response:

{
  "intent": "compliment",
  "intentNamespace": "app",
  "language": "fr",
  "entities": [],
  "notRetainedEntities": [],
  "intentProbability": 0.2773954458338288,
  "entitiesProbability": 1,
  "retainedQuery": "test bouton",
  "otherIntentsProbabilities": {
    "app:test_boutons": 0.20721793662888438,
    "app:insulte": 0.14216223546979748

**Comment by vsct-jburet** [comment]
Corrigé mais seulement pour les nouvelles analyses, pas les anciennes
