### ISSUE TITLE
[Doc] Explain Tock Studio roles

### ISSUE THREAD

**Issue by MorganeAbadie** [theopenconversationkit/tock#753]
Bonjour,

Je souhaiterais savoir si l'évolution suivante est prévue ou s'il est possible de l'envisager.
Etant donné que nous allons donner accès à Tock Studio à nos métiers, nous aimerions avoir des droits différents selon les profils utilisateurs, et donc, pouvoir restreindre l'accès à certains onglets.

Merci d'avance.
Morgane

**Comment by vsct-jburet** [comment]
@MorganeAbadie Il y a déjà 4 types de droits:

- nlpUser : a accès à la partie nlp
-botUser : a accès à la partie bot
-admin: a accès à l'ensemble des fonctionnalités sauf les points les plus sensibles
- technicalAdmin: a accès à l'ensemble des fonctionnalités

Si besoin  d'une granularité plus fine c'est possible mais il nous faudrait quelques exemples de profils.

**Comment by elebescond** [comment]
@vsct-jburet @MorganeAbadie je pense que cette partie n'est pas documentée sur le site ? On peut profiter de ce ticket pour documenter la fonctionnalité ...

**Comment by MorganeAbadie** [comment]
Bonjour,

Merci pour votre retour.
Effectivement, une documentation à ce sujet serait la bienvenue :). Notre développeur avait commencé à regarder comment assigner des droits différents et à quoi ils correspondaient exactement mais n'a pas trouvé tout de suite et est ensuite passé à autre chose.
Cette analyse nous permettrait de répondre à la question sur la granularité, à savoir si nous avons besoin de profils supplémentaires.

**Comment by francoisno** [comment]
https://doc.tock.ai/tock/fr/admin/securite/#roles
