### ISSUE TITLE
Stories Dump - Buttons not functioning

### ISSUE THREAD

**Issue by MorganeAbadie** [theopenconversationkit/tock#768]
Bonjour,

Nous avons détecté un problème avec les dumps de story sur les boutons.
1. Sur l'environnement de recette, les stories sont configurées avec des boutons.
2. Nous faisons un export dump des stories de la recette
3. Nous faisons un import de ce dump sur l'environnement de préprod
4. Nous testons le bon fonctionnement de l'import (onglet "test") sur le préprod et il s'avère que les boutons n'apparaissent pas dans le message renvoyé par le bot
5. Nous vérifions la bonne configuration des stories (Build > Search Story) : les boutons sont bien présents. Mais pour qu'il soit de nouveau fonctionnels, il faut que nous revalidions la story en cliquant sur "update story".
6. Alors les boutons sont de nouveau fonctionnels sur le test

Nous avons fait la montée de version 19.9.3 et pensions que ce problème serait réglé via la correction sur les boutons où il fallait resélectionner manuellement l'intent (https://github.com/theopenconversationkit/tock/issues/736) mais ce n'est pas le cas car la nouvelle version a toujours ce problème.

Merci d'avance.
Morgane

**Comment by vsct-jburet** [comment]
Corrigé sur la plateforme de démo - release prévue lundi ou mardi
