### ISSUE TITLE
Hypertext link

### ISSUE THREAD

**Issue by MorganeAbadie** [theopenconversationkit/tock#770]
Bonjour,

Est-il possible d'envisager une évolution dans Tock Studio permettant d'insérer des liens hypertextes ?

Merci.
Morgane

**Comment by vsct-jburet** [comment]
@MorganeAbadie C'est normalement déjà le cas : il est possible dans le format card de rajouter des actions avec url. Souhaites tu rajouter une url à un autre endroit?

**Comment by MorganeAbadie** [comment]
Bonjour Julien,
Je n'avais effectivement pas vu cette fonctionnalité, merci.
En revanche, je viens de tester et ça ne fonctionne pas. Le title et l'url indiqué dans la story de s'affichent pas.

**Comment by vsct-jburet** [comment]
@MorganeAbadie Pour moi le lien s'affiche (cf cope d'écran) : Dans quel contexte ne s'affiche t'il pas ? 
![image](https://user-images.githubusercontent.com/12413454/76144862-96ca2080-6084-11ea-8483-61d9ba217abb.png)

**Comment by MorganeAbadie** [comment]
Bonjour Julien,

Je viens de refaire un test sur la version de démo et j'ai compris pourquoi le lien ne s'affiche pas chez moi : c'est lorsque qu'il n'y a pas de Title  ou Sub Title de renseigné.
Or tous les champs sont indiqués comme optionnels, le lien hypertext devrait donc s'afficher même si c'est 2 premiers champs ne sont pas remplis.

**Comment by MorganeAbadie** [comment]
![lien_hypertext](https://user-images.githubusercontent.com/54838256/76291666-dc1d6680-62ad-11ea-98b6-e3865a6f6f4f.PNG)

**Comment by vsct-jburet** [comment]
@MorganeAbadie sur quel type de connecteur le test est-il effectué? Le web? Car chaque connecteur s'adapte à ses formats spécifiques

**Comment by MorganeAbadie** [comment]
oui, j'ai utilisé le connecteur web.

**Comment by francoisno** [comment]
I close this issue, the title/subtitle mandatory issue is tracked by #931
