### ISSUE TITLE
[Studio] Create required intents when importing stories

### ISSUE THREAD

**Issue by francoisno** [theopenconversationkit/tock#780]
When importing a story, required intents are not created/updated. It may result in non-functional stories after import. Plus the new story mentions intents, which do not exist in NLU tabs.

The original intents and sentences are not included in the story dump. Nevertheless, dump info includes intent name, which should be enough to recreate default intents (new ID, same name, default category and no sentences)  when necessary ie. when intent name not found.

**Comment by vsct-jburet** [comment]
@francoisno Intents are already created if not present - but not updated. Do you have a case to reproduce? ;)

**Comment by vsct-jburet** [comment]
Ok, I think I have found the problem : I do not create the sentence for the main intent, and I do not update the sentence if the sentence is already in the model. I'm going to fix it
