### ISSUE TITLE
Upload de Dump de story recliquer sur les intents

### ISSUE THREAD

**Issue by francoisno** [theopenconversationkit/tock#783]
(Copy of the former repo issue voyages-sncf-technologies/tock#9 reported by @LiviaHaulot.)

Bonjour,

Quand nous faisons un upload de dump de story nous sommes obligés de recliquer sur tous les intents des Actions.

Bien cordialement,

Livia Haulot

**Comment by francoisno** [comment]
Also see #768

**Comment by vsct-jburet** [comment]
Corrigé
