### ISSUE TITLE
Problème paramétrage build et test

### ISSUE THREAD

**Issue by LiviaHaulot** [theopenconversationkit/tock#797]
Bonjour,

J'ai paramétré dans notre bot la semaine dernière une story avec plusieurs target intent. Je l'ai testé aujourd'hui et j'ai vu des différences entre ce que j'ai paramétré et ce qui apparaît réellement dans le menu test.

Dans cette capture d'écran vous voyez que le premier bouton action a pour User phrase : "Cas particulier des colonnes montantes".

![pb de paramétrage du build (menu build)](https://user-images.githubusercontent.com/39556657/75240799-3c4bdd00-57c5-11ea-952c-2006dd98e1e0.PNG)

Cependant, quand je teste la story, ce n'est pas la user phrase paramétrée qui apparaît mais "c".

![pb paramétrage build (menu test)](https://user-images.githubusercontent.com/39556657/75246926-14627680-57d1-11ea-89de-216ef49ebbe7.PNG)

Au début nous pensions à des erreurs de paramétrages, mais ces problématiques nous arrivent assez souvent notamment sur les storys avec des actions : 
- des user phrases différentes de celles paramétrées
- des réponses paramétrées dans le build mais qui n'apparaissent pas dans le test
- des storys différentes qui sont appelées 

De plus comme vous pouvez le voir dans le test les boutons actions ne s'adaptent pas pas au nombre de caractères.

**Comment by vsct-jburet** [comment]
@LiviaHaulot En effet la taille des boutons dans le module de test est limitée - je vais corriger.

Pour les modifications de libellés, je ne reproduis pas. Avez-vous un exemple sur tock demo? Merci

**Comment by vsct-jburet** [comment]
@LiviaHaulot à priori le problème de non qualification de phrase est corrigé sur la plateforme de démo - une release est prévue lundi ou mardi.

J'ai pu reproduire également le problème de libellé d'action qui disparaissait : Il faut d'abord importer les réponses (format json, attention seules les réponses validées sont importées) avant d'importer les stories. J'admets que ce n'est pas très intuitif, ce sera corrigé dans #779
