### ISSUE TITLE
Tock kernel supports FATFS?

### ISSUE THREAD

**Issue by chongyang0515** [theopenconversationkit/tock#934]
Reading SD card files is important for most embedded devices, and I wonder if Tock has any plans to support fatfs, which my current project needs and, if possible, can be developed in collaboration with each other.

**Comment by francoisno** [comment]
Hello @chongyang0515,
This is the GitHub project/issues for _Tock.ai_ (aka The Open Conversation Kit).
For _Tock Embedded OS_, please rather use https://github.com/tock/tock/issues 
Regards
