### ISSUE TITLE
[Tock Studio] Bot analytics

### ISSUE THREAD

**Issue by bakic** [theopenconversationkit/tock#942]
Add dashboards for bot analytics, for example users and messages per connector

**Comment by francoisno** [comment]
I was thinking about it!
Would you add it somewhere in _Bot Flow_ or as a new tab/view ?

Nice-to-have features, to be discussed:

- Trafic and users by story, intent, connector...
- (Sortable) Table + Histogram
- Filter by date / Visualize evolution
- CSV export

**Comment by bakic** [comment]
I think that there will be a new menu called Analytics that will group the botflow and other new tabs related to bot stats.
to be discussed

**Comment by francoisno** [comment]
Nice work @bakic. I have added date-range calendar to Bot Flow (#969), now as discussed I will try to refactor the new Analytics view from your branch to use shared calendar and possibly some Admin service logic.
