### ISSUE TITLE
[Tock Studio] remove angular material design lib

### ISSUE THREAD

**Issue by vsct-jburet** [theopenconversationkit/tock#976]

**Comment by francoisno** [comment]
You mean move Material components to Nebular, for instance `matTooltip` to `nbTooltip` ?

**Comment by vsct-jburet** [comment]
> You mean move Material components to Nebular, for instance `matTooltip` to `nbTooltip` ?

yes

**Comment by francoisno** [comment]
Dark mode is very convenient to spot Material>>Nebular remaining tasks ;-)

**Comment by rkuffer** [comment]
This PR finishes by replacing all Material element occurrences with their Nebular equivalents :
https://github.com/theopenconversationkit/tock/pull/1545
