### ISSUE TITLE
[Tock Studio] Story Search can be slow when many stories

### ISSUE THREAD

**Issue by MorganeAbadie** [theopenconversationkit/tock#984]
Bonjour François,

Comme discuté ensemble, la partie search stories de l'admin lague pas mal lorsqu'on a beaucoup de stories.
A la fois pour l'affichage complet des stories mais également entre chaque lettre saisie pour afficher une story en particulier.

Merci d'avance pour ton aide

**Comment by francoisno** [comment]
Solutions potentielles : 

- Tempo sur le champ _Search Stories_ avant de lancer la recherche
- Ou bouton pour déclencher explicitement la recherche
- Pagination des résultats dans la page
- ...

**Comment by vsct-jburet** [comment]
J'ai implémenté une solution avec ce composant https://akveo.github.io/nebular/docs/components/tree-grid/overview#nbtreegridcomponent qui règle le problème me semble t'il
