### ISSUE TITLE
[Tock Studio] Problème import stories après export

### ISSUE THREAD

**Issue by MorganeAbadie** [theopenconversationkit/tock#988]
Bonjour,

J'ai exporté des stories depuis un chatbot que j'ai ensuite importées dans un autre.
J'ai remarqué que parfois, l'import se fait mal :
- des "" sot ajoutés dans la story importées
- lorsqu'il y a plusieurs bulles de réponse et des boutons, la story importées n'est pas au bon format.

Je vous joins des captures écrans plus parlantes car c'est difficile à expliquer.
Story 1 exportée
![pb_import_stories_1](https://user-images.githubusercontent.com/54838256/86584755-b2d3c500-bf85-11ea-9b25-6480702b7025.PNG)
Story 1 après import
![pb_import_stories_1bis](https://user-images.githubusercontent.com/54838256/86584758-b404f200-bf85-11ea-9f79-141374c13730.PNG)

Story 2 exportée
![pb_import_stories_2](https://user-images.githubusercontent.com/54838256/86584759-b49d8880-bf85-11ea-981c-c49ef4a95b9e.PNG)
Story 2 après import
![pb_import_stories_2bis](https://user-images.githubusercontent.com/54838256/86584760-b5361f00-bf85-11ea-958c-30ad34ce0e95.PNG)

Ce souci d'import n'est pas toujours présent, c'est comme si parfois, le json généré par l'export ne se faisait pas bien et renvoyait ces erreurs mentionnées au moment de l'import dans l'autre chatbot.

Je ne peux pas vous joindre le json dans ce ticket mais je peux fournir par email si besoin.

Merci.
Morgane

**Comment by francoisno** [comment]
Bonjour @MorganeAbadie,

Pour le moment je n'arrive pas à reproduire le problème en créant des stories similaires - avec des actions, des caractères spéciaux, etc.
Aurais-tu un exemple de story ayant ce problème sur demo.tock.ai pour que je puisse débugger ?

**Comment by MorganeAbadie** [comment]
Bonjour @francoisno,

Tu peux regarder les stories de la catégorie "Switch humain" que je viens d'importer.
Dis-moi si tu veux que je t'envoies par email le json que j'avais exporté.

**Comment by MorganeAbadie** [comment]
Bonjour @francoisno ,

As-tu pu poursuivre les tests suite aux stories que je t'avais indiquées ?

Merci,
Morgane

**Comment by MorganeAbadie** [comment]
Bonjour @francoisno 

Nous avons fait de nouveaux tests d'export / import suite à l'installation de la dernière version TOCK mais le problème est toujours présent.
Avez-vous pu poursuivre l'investigation sur le sujet ?

Merci,
Morgane

**Comment by MorganeAbadie** [comment]
Bonjour @francoisno,

Je rebondis sur ce ticket car j'ai constaté une anomalie connexe à celle-ci, sur la génération des json.
En effet, lorsque je modifie une story dans Tock Studio et que je génère un json, ce dernier ne prend pas en compte les modifications. Le dumps de stories que nous faisons ne reflètent donc pas la réalité de la base et ne peuvent pas être importés manuellement dans un autre environnement (ex: de recette à préprod).

**Comment by ahmedBUSF** [comment]
> 
> 
> Bonjour,
> 
> J'ai exporté des stories depuis un chatbot que j'ai ensuite importées dans un autre.
> J'ai remarqué que parfois, l'import se fait mal :
> 
>     * des "" sot ajoutés dans la story importées
> 
>     * lorsqu'il y a plusieurs bulles de réponse et des boutons, la story importées n'est pas au bon format.
> 
> 
> Je vous joins des captures écrans plus parlantes car c'est difficile à expliquer.
> Story 1 exportée
> ![pb_import_stories_1](https://user-images.githubusercontent.com/54838256/86584755-b2d3c500-bf85-11ea-9b25-6480702b7025.PNG)
> Story 1 après import
> ![pb_import_stories_1bis](https://user-images.githubusercontent.com/54838256/86584758-b404f200-bf85-11ea-9f79-141374c13730.PNG)
> 
> Story 2 exportée
> ![pb_import_stories_2](https://user-images.githubusercontent.com/54838256/86584759-b49d8880-bf85-11ea-981c-c49ef4a95b9e.PNG)
> Story 2 après import
> ![pb_import_stories_2bis](https://user-images.githubusercontent.com/54838256/86584760-b5361f00-bf85-11ea-958c-30ad34ce0e95.PNG)
> 
> Ce souci d'import n'est pas toujours présent, c'est comme si parfois, le json généré par l'export ne se faisait pas bien et renvoyait ces erreurs mentionnées au moment de l'import dans l'autre chatbot.
> 
> Je ne peux pas vous joindre le json dans ce ticket mais je peux fournir par email si besoin.
> 
> J'ai le mm problème en faisant un export de la BDD coté mongodb

**Comment by francoisno** [comment]
Recent issues seem caused by #1067, 'on it ASAP.

**Comment by francoisno** [comment]
Thx to your latest dumps/scenario @MorganeAbadie I have found 2 bugs leading to story/label import errors: #1067 and #1076 
Both should be fixed by #1073
