### ISSUE TITLE
Problème affichage pièces jointes et boutons

### ISSUE THREAD

**Issue by MorganeAbadie** [theopenconversationkit/tock#989]
Bonjour,

Lorsque dans une story il y a à la fois des PJ et des boutons, l'affichage ne se fait pas correctement et pas dans le bon ordre comme vous pouvez le constater ci-dessous :
- les boutons sont affichés avant la PJ alors qu'ils devraient l'être après
- s'il y a plusieurs PJ, les boutons se doublonnent

![affichage_pj_boutons](https://user-images.githubusercontent.com/54838256/86604995-69e03880-bfa6-11ea-8caa-a59ffbe10f71.PNG)

Merci,
Morgane

**Comment by vsct-jburet** [comment]
- Le problème d'affichage avant la pj doit être lié à l'implémentation de votre widget web. Rapprochez vous de l'équipe ayant implémenté le widget
- le problème de double affichage a été corrigé dans #966 et sera disponible dans la prochaine release

**Comment by dabadiesimon** [comment]
Bonjour @vsct-jburet , 
L'ordre d'affichage respecte l'ordre du retour de l'API. Réponse du bot ci-dessous:

```
{"responses":[
{"text":"Vous trouverez toutes les informations sur les coffrets et bornes CIBE du segment C5 dans les documents ci-dessous.","version":"1"},
{"buttons":[{"clazz":"postback_button","title":"Dimensions coffret CIBE C5","type":"postback"},{"clazz":"postback_button","title":"Dimensions niche CIBE C5","type":"postback"}],
"card":{"title":"Références","subTitle":"Références","file":{"url":"http://dir2bot:8080/f/appe924ecdb-8eb2-4678-9bd5-6715a2c62c82.pdf","name":"Sequelec Coffrets CIBE C5.pdf","type":"file"},
"buttons":[]},"version":"1"},{"buttons":[{"clazz":"postback_button","title":"Dimensions coffret CIBE C5","type":"postback"},{"clazz":"postback_button","title":"Dimensions niche CIBE C5","type":"postback"}],
"card":{"title":"Informations Coffrets CIBE C5","subTitle":"Informations Coffrets CIBE C5","file":{"url":"http://dir2bot:8080/f/appd648106a-9f58-41a0-a298-64506a82c36c.pdf","name":"Coffrets CIBE C5.pdf","type":"file"},
"buttons":[]},"version":"1"}]}
```

Selon nous, l'ordre est incohérent avec l'ordre configuré dans le Story Builder: 
![image](https://user-images.githubusercontent.com/52737632/86759043-8fbc1a80-c044-11ea-8ea6-1b55e829620d.png)

Qu'en penses-tu ? 
Merci,
Simon
